#pragma once

#include"sockbuffer.h"
#include"communicate.h"
#include"gameflow.h"
#include"killer.h"
#include"thief.h"
#include"magician.h"
#include"king.h"
#include"abbot.h"
#include"trader.h"
#include"architect.h"
#include"warload.h"
#include"tool.h"

#include"library.h"
#include"dragongate.h"
#include"graveyard.h"
#include"hauntedcity.h"
#include"magicschool.h"
#include"laboratory.h"
#include"workshop.h"
#include"observatory.h"
#include"university.h"
#include"keep.h"
#include"greatwall.h"